# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("services.proto", :syntax => :proto3) do
    add_message "jjogaegi.RunConfig" do
      optional :parser, :string, 1
      optional :formatter, :string, 2
      map :options, :string, :string, 3
    end
    add_message "jjogaegi.RunRequest" do
      optional :config, :message, 1, "jjogaegi.RunConfig"
      optional :input, :bytes, 2
    end
    add_message "jjogaegi.RunResponse" do
      optional :output, :bytes, 1
    end
  end
end

module Jjogaegi
  RunConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("jjogaegi.RunConfig").msgclass
  RunRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("jjogaegi.RunRequest").msgclass
  RunResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("jjogaegi.RunResponse").msgclass
end
