# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: services.proto for package 'proto'

require 'grpc'
require 'services_pb'

module Proto
  module Jjogaegi
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'proto.Jjogaegi'

      # Runs a single input
      rpc :Run, RunRequest, RunResponse
      # Runs a stream of inputs. Only the first config is considered; thereafter, only the input accepted.
      rpc :RunStream, stream(RunRequest), stream(RunResponse)
    end

    Stub = Service.rpc_stub_class
  end
end
