// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RunRequest struct {
	Input                string   `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Parser               string   `protobuf:"bytes,2,opt,name=parser,proto3" json:"parser,omitempty"`
	Formatter            string   `protobuf:"bytes,3,opt,name=formatter,proto3" json:"formatter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunRequest) Reset()         { *m = RunRequest{} }
func (m *RunRequest) String() string { return proto.CompactTextString(m) }
func (*RunRequest) ProtoMessage()    {}
func (*RunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{0}
}

func (m *RunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunRequest.Unmarshal(m, b)
}
func (m *RunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunRequest.Marshal(b, m, deterministic)
}
func (m *RunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunRequest.Merge(m, src)
}
func (m *RunRequest) XXX_Size() int {
	return xxx_messageInfo_RunRequest.Size(m)
}
func (m *RunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunRequest proto.InternalMessageInfo

func (m *RunRequest) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *RunRequest) GetParser() string {
	if m != nil {
		return m.Parser
	}
	return ""
}

func (m *RunRequest) GetFormatter() string {
	if m != nil {
		return m.Formatter
	}
	return ""
}

type RunResponse struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunResponse) Reset()         { *m = RunResponse{} }
func (m *RunResponse) String() string { return proto.CompactTextString(m) }
func (*RunResponse) ProtoMessage()    {}
func (*RunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{1}
}

func (m *RunResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunResponse.Unmarshal(m, b)
}
func (m *RunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunResponse.Marshal(b, m, deterministic)
}
func (m *RunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunResponse.Merge(m, src)
}
func (m *RunResponse) XXX_Size() int {
	return xxx_messageInfo_RunResponse.Size(m)
}
func (m *RunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunResponse proto.InternalMessageInfo

func (m *RunResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func init() {
	proto.RegisterType((*RunRequest)(nil), "proto.RunRequest")
	proto.RegisterType((*RunResponse)(nil), "proto.RunResponse")
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor_bedfbfc9b54e5600) }

var fileDescriptor_bedfbfc9b54e5600 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0x31, 0x0b, 0xc2, 0x40,
	0x0c, 0x46, 0xad, 0xa5, 0xc5, 0xc6, 0xc9, 0x20, 0x52, 0xc4, 0x41, 0x0a, 0x82, 0x53, 0x07, 0xdd,
	0xfc, 0x09, 0x8e, 0x37, 0xb9, 0x56, 0x89, 0xa5, 0x82, 0x97, 0x33, 0x97, 0xfb, 0xff, 0xe2, 0xb5,
	0x70, 0x4e, 0xe1, 0xbd, 0xc0, 0xe3, 0x03, 0xe8, 0xc5, 0x3d, 0x5a, 0x27, 0xac, 0x8c, 0x45, 0x3c,
	0xcd, 0x0d, 0xc0, 0x04, 0x6b, 0xe8, 0x13, 0xc8, 0x2b, 0xae, 0xa1, 0x18, 0xac, 0x0b, 0x5a, 0x67,
	0xfb, 0xec, 0x58, 0x99, 0x11, 0x70, 0x03, 0xa5, 0xeb, 0xc4, 0x93, 0xd4, 0xf3, 0xa8, 0x27, 0xc2,
	0x1d, 0x54, 0x4f, 0x96, 0x77, 0xa7, 0x4a, 0x52, 0xe7, 0xf1, 0x95, 0x44, 0x73, 0x80, 0x65, 0x2c,
	0x7b, 0xc7, 0xd6, 0xd3, 0x2f, 0xc2, 0x41, 0x53, 0x7b, 0xa2, 0xd3, 0x05, 0x16, 0xd7, 0x17, 0xf7,
	0x1d, 0xf5, 0x03, 0xb6, 0x90, 0x9b, 0x60, 0x71, 0x35, 0x4e, 0x6c, 0xd3, 0xb0, 0x2d, 0xfe, 0xab,
	0xb1, 0xd8, 0xcc, 0xee, 0x65, 0x94, 0xe7, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaf, 0xb8, 0xb4,
	0xbb, 0xd8, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JjogaegiClient is the client API for Jjogaegi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JjogaegiClient interface {
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
}

type jjogaegiClient struct {
	cc *grpc.ClientConn
}

func NewJjogaegiClient(cc *grpc.ClientConn) JjogaegiClient {
	return &jjogaegiClient{cc}
}

func (c *jjogaegiClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, "/proto.Jjogaegi/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JjogaegiServer is the server API for Jjogaegi service.
type JjogaegiServer interface {
	Run(context.Context, *RunRequest) (*RunResponse, error)
}

// UnimplementedJjogaegiServer can be embedded to have forward compatible implementations.
type UnimplementedJjogaegiServer struct {
}

func (*UnimplementedJjogaegiServer) Run(ctx context.Context, req *RunRequest) (*RunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}

func RegisterJjogaegiServer(s *grpc.Server, srv JjogaegiServer) {
	s.RegisterService(&_Jjogaegi_serviceDesc, srv)
}

func _Jjogaegi_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JjogaegiServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Jjogaegi/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JjogaegiServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Jjogaegi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Jjogaegi",
	HandlerType: (*JjogaegiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _Jjogaegi_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}
