// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RunConfig struct {
	Parser               string            `protobuf:"bytes,1,opt,name=parser,proto3" json:"parser,omitempty"`
	Formatter            string            `protobuf:"bytes,2,opt,name=formatter,proto3" json:"formatter,omitempty"`
	Options              map[string]string `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RunConfig) Reset()         { *m = RunConfig{} }
func (m *RunConfig) String() string { return proto.CompactTextString(m) }
func (*RunConfig) ProtoMessage()    {}
func (*RunConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{0}
}

func (m *RunConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunConfig.Unmarshal(m, b)
}
func (m *RunConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunConfig.Marshal(b, m, deterministic)
}
func (m *RunConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunConfig.Merge(m, src)
}
func (m *RunConfig) XXX_Size() int {
	return xxx_messageInfo_RunConfig.Size(m)
}
func (m *RunConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RunConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RunConfig proto.InternalMessageInfo

func (m *RunConfig) GetParser() string {
	if m != nil {
		return m.Parser
	}
	return ""
}

func (m *RunConfig) GetFormatter() string {
	if m != nil {
		return m.Formatter
	}
	return ""
}

func (m *RunConfig) GetOptions() map[string]string {
	if m != nil {
		return m.Options
	}
	return nil
}

type RunRequest struct {
	Config               *RunConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Input                []byte     `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RunRequest) Reset()         { *m = RunRequest{} }
func (m *RunRequest) String() string { return proto.CompactTextString(m) }
func (*RunRequest) ProtoMessage()    {}
func (*RunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{1}
}

func (m *RunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunRequest.Unmarshal(m, b)
}
func (m *RunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunRequest.Marshal(b, m, deterministic)
}
func (m *RunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunRequest.Merge(m, src)
}
func (m *RunRequest) XXX_Size() int {
	return xxx_messageInfo_RunRequest.Size(m)
}
func (m *RunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunRequest proto.InternalMessageInfo

func (m *RunRequest) GetConfig() *RunConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *RunRequest) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

type RunResponse struct {
	Output               []byte   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunResponse) Reset()         { *m = RunResponse{} }
func (m *RunResponse) String() string { return proto.CompactTextString(m) }
func (*RunResponse) ProtoMessage()    {}
func (*RunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{2}
}

func (m *RunResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunResponse.Unmarshal(m, b)
}
func (m *RunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunResponse.Marshal(b, m, deterministic)
}
func (m *RunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunResponse.Merge(m, src)
}
func (m *RunResponse) XXX_Size() int {
	return xxx_messageInfo_RunResponse.Size(m)
}
func (m *RunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunResponse proto.InternalMessageInfo

func (m *RunResponse) GetOutput() []byte {
	if m != nil {
		return m.Output
	}
	return nil
}

func init() {
	proto.RegisterType((*RunConfig)(nil), "proto.RunConfig")
	proto.RegisterMapType((map[string]string)(nil), "proto.RunConfig.OptionsEntry")
	proto.RegisterType((*RunRequest)(nil), "proto.RunRequest")
	proto.RegisterType((*RunResponse)(nil), "proto.RunResponse")
}

func init() { proto.RegisterFile("services.proto", fileDescriptor_8e16ccb8c5307b32) }

var fileDescriptor_8e16ccb8c5307b32 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xdd, 0x86, 0x46, 0x33, 0x29, 0x52, 0x07, 0x91, 0x50, 0x14, 0x4a, 0x40, 0xc8, 0x29,
	0x48, 0x3c, 0x58, 0x7a, 0x15, 0x2f, 0x22, 0x08, 0xeb, 0x13, 0xc4, 0x32, 0x0d, 0x51, 0xbb, 0x1b,
	0x77, 0x67, 0x0b, 0x7d, 0x31, 0x9f, 0x4f, 0xb2, 0x59, 0x6d, 0xf1, 0xe4, 0x69, 0xf7, 0x9f, 0x7f,
	0xe6, 0xff, 0x86, 0x81, 0x53, 0x4b, 0x66, 0xdb, 0xae, 0xc8, 0x96, 0x9d, 0xd1, 0xac, 0x71, 0xec,
	0x9f, 0xfc, 0x4b, 0x40, 0x22, 0x9d, 0xba, 0xd7, 0x6a, 0xdd, 0x36, 0x78, 0x01, 0x71, 0x57, 0x1b,
	0x4b, 0x26, 0x13, 0x73, 0x51, 0x24, 0x32, 0x28, 0xbc, 0x84, 0x64, 0xad, 0xcd, 0xa6, 0x66, 0x26,
	0x93, 0x8d, 0xbc, 0xb5, 0x2f, 0xe0, 0x1d, 0x1c, 0xeb, 0x8e, 0x5b, 0xad, 0x6c, 0x16, 0xcd, 0xa3,
	0x22, 0xad, 0xae, 0x06, 0x46, 0xf9, 0x1b, 0x5c, 0x3e, 0x0f, 0xfe, 0x83, 0x62, 0xb3, 0x93, 0x3f,
	0xdd, 0xb3, 0x25, 0x4c, 0x0e, 0x0d, 0x9c, 0x42, 0xf4, 0x4e, 0xbb, 0xc0, 0xee, 0xbf, 0x78, 0x0e,
	0xe3, 0x6d, 0xfd, 0xe1, 0x28, 0x40, 0x07, 0xb1, 0x1c, 0x2d, 0x44, 0xfe, 0x04, 0x20, 0x9d, 0x92,
	0xf4, 0xe9, 0xc8, 0x32, 0x16, 0x10, 0xaf, 0x3c, 0xc9, 0x0f, 0xa7, 0xd5, 0xf4, 0xef, 0x06, 0x32,
	0xf8, 0x7d, 0x62, 0xab, 0x3a, 0xc7, 0x3e, 0x71, 0x22, 0x07, 0x91, 0x5f, 0x43, 0xea, 0xd3, 0x6c,
	0xa7, 0x95, 0xa5, 0xfe, 0x0e, 0xda, 0x71, 0xdf, 0x25, 0x7c, 0x57, 0x50, 0x15, 0xc3, 0xc9, 0xe3,
	0x9b, 0x6e, 0x6a, 0x6a, 0x5a, 0x2c, 0x21, 0x92, 0x4e, 0xe1, 0xd9, 0x9e, 0x14, 0x96, 0x99, 0xe1,
	0x61, 0x69, 0x48, 0xcc, 0x8f, 0x70, 0xe1, 0x0f, 0xfd, 0xc2, 0x86, 0xea, 0xcd, 0xbf, 0xa7, 0x0a,
	0x71, 0x23, 0x5e, 0x63, 0x6f, 0xdc, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x85, 0x17, 0xea, 0xae,
	0xc3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JjogaegiClient is the client API for Jjogaegi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JjogaegiClient interface {
	// Runs a single input
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	// Runs a stream of inputs. Only the first config is considered; thereafter, only the input accepted.
	RunStream(ctx context.Context, opts ...grpc.CallOption) (Jjogaegi_RunStreamClient, error)
}

type jjogaegiClient struct {
	cc *grpc.ClientConn
}

func NewJjogaegiClient(cc *grpc.ClientConn) JjogaegiClient {
	return &jjogaegiClient{cc}
}

func (c *jjogaegiClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, "/proto.Jjogaegi/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jjogaegiClient) RunStream(ctx context.Context, opts ...grpc.CallOption) (Jjogaegi_RunStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Jjogaegi_serviceDesc.Streams[0], "/proto.Jjogaegi/RunStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &jjogaegiRunStreamClient{stream}
	return x, nil
}

type Jjogaegi_RunStreamClient interface {
	Send(*RunRequest) error
	Recv() (*RunResponse, error)
	grpc.ClientStream
}

type jjogaegiRunStreamClient struct {
	grpc.ClientStream
}

func (x *jjogaegiRunStreamClient) Send(m *RunRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *jjogaegiRunStreamClient) Recv() (*RunResponse, error) {
	m := new(RunResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// JjogaegiServer is the server API for Jjogaegi service.
type JjogaegiServer interface {
	// Runs a single input
	Run(context.Context, *RunRequest) (*RunResponse, error)
	// Runs a stream of inputs. Only the first config is considered; thereafter, only the input accepted.
	RunStream(Jjogaegi_RunStreamServer) error
}

// UnimplementedJjogaegiServer can be embedded to have forward compatible implementations.
type UnimplementedJjogaegiServer struct {
}

func (*UnimplementedJjogaegiServer) Run(ctx context.Context, req *RunRequest) (*RunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (*UnimplementedJjogaegiServer) RunStream(srv Jjogaegi_RunStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method RunStream not implemented")
}

func RegisterJjogaegiServer(s *grpc.Server, srv JjogaegiServer) {
	s.RegisterService(&_Jjogaegi_serviceDesc, srv)
}

func _Jjogaegi_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JjogaegiServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Jjogaegi/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JjogaegiServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Jjogaegi_RunStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(JjogaegiServer).RunStream(&jjogaegiRunStreamServer{stream})
}

type Jjogaegi_RunStreamServer interface {
	Send(*RunResponse) error
	Recv() (*RunRequest, error)
	grpc.ServerStream
}

type jjogaegiRunStreamServer struct {
	grpc.ServerStream
}

func (x *jjogaegiRunStreamServer) Send(m *RunResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *jjogaegiRunStreamServer) Recv() (*RunRequest, error) {
	m := new(RunRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Jjogaegi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Jjogaegi",
	HandlerType: (*JjogaegiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _Jjogaegi_Run_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunStream",
			Handler:       _Jjogaegi_RunStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "services.proto",
}
